//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LibraryApp.ServiceDbBuilder {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceDbBuilder.IServiceDbBuilder")]
    public interface IServiceDbBuilder {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceDbBuilder/GetData", ReplyAction="http://tempuri.org/IServiceDbBuilder/GetDataResponse")]
        string GetData(int value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceDbBuilder/GetData", ReplyAction="http://tempuri.org/IServiceDbBuilder/GetDataResponse")]
        System.Threading.Tasks.Task<string> GetDataAsync(int value);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServiceDbBuilderChannel : LibraryApp.ServiceDbBuilder.IServiceDbBuilder, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServiceDbBuilderClient : System.ServiceModel.ClientBase<LibraryApp.ServiceDbBuilder.IServiceDbBuilder>, LibraryApp.ServiceDbBuilder.IServiceDbBuilder {
        
        public ServiceDbBuilderClient() {
        }
        
        public ServiceDbBuilderClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServiceDbBuilderClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceDbBuilderClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceDbBuilderClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string GetData(int value) {
            return base.Channel.GetData(value);
        }
        
        public System.Threading.Tasks.Task<string> GetDataAsync(int value) {
            return base.Channel.GetDataAsync(value);
        }
    }
}
