//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LibraryApp.ServiceBookManagement {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceBookManagement.IServiceBookManagement")]
    public interface IServiceBookManagement {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceBookManagement/IsBookDeleted", ReplyAction="http://tempuri.org/IServiceBookManagement/IsBookDeletedResponse")]
        bool IsBookDeleted(int bookId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceBookManagement/IsBookDeleted", ReplyAction="http://tempuri.org/IServiceBookManagement/IsBookDeletedResponse")]
        System.Threading.Tasks.Task<bool> IsBookDeletedAsync(int bookId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceBookManagement/DeleteBook", ReplyAction="http://tempuri.org/IServiceBookManagement/DeleteBookResponse")]
        bool DeleteBook(int bookId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceBookManagement/DeleteBook", ReplyAction="http://tempuri.org/IServiceBookManagement/DeleteBookResponse")]
        System.Threading.Tasks.Task<bool> DeleteBookAsync(int bookId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceBookManagement/RestoreBook", ReplyAction="http://tempuri.org/IServiceBookManagement/RestoreBookResponse")]
        bool RestoreBook(int bookId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceBookManagement/RestoreBook", ReplyAction="http://tempuri.org/IServiceBookManagement/RestoreBookResponse")]
        System.Threading.Tasks.Task<bool> RestoreBookAsync(int bookId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceBookManagement/AddNewBook", ReplyAction="http://tempuri.org/IServiceBookManagement/AddNewBookResponse")]
        void AddNewBook(string textBoxRating, string textBoxLanguage, string textBoxRates, string textBoxAuthor, string textBoxPrice, string textBoxCharacters, string textBoxGenres, string textBoxSetting, string textBoxDescription, string textBoxTitle, string textBoxSeries, string textBoxPages, string textBoxFormat, string textBoxPublisher, string textBoxLink);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceBookManagement/AddNewBook", ReplyAction="http://tempuri.org/IServiceBookManagement/AddNewBookResponse")]
        System.Threading.Tasks.Task AddNewBookAsync(string textBoxRating, string textBoxLanguage, string textBoxRates, string textBoxAuthor, string textBoxPrice, string textBoxCharacters, string textBoxGenres, string textBoxSetting, string textBoxDescription, string textBoxTitle, string textBoxSeries, string textBoxPages, string textBoxFormat, string textBoxPublisher, string textBoxLink);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceBookManagement/EditBook", ReplyAction="http://tempuri.org/IServiceBookManagement/EditBookResponse")]
        void EditBook(
                    int bookId, 
                    string textBoxRating, 
                    string textBoxLanguage, 
                    string textBoxRates, 
                    string textBoxAuthor, 
                    string textBoxPrice, 
                    string textBoxCharacters, 
                    string textBoxGenres, 
                    string textBoxSetting, 
                    string textBoxDescription, 
                    string textBoxTitle, 
                    string textBoxSeries, 
                    string textBoxPages, 
                    string textBoxFormat, 
                    string textBoxPublisher, 
                    string textBoxLink);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceBookManagement/EditBook", ReplyAction="http://tempuri.org/IServiceBookManagement/EditBookResponse")]
        System.Threading.Tasks.Task EditBookAsync(
                    int bookId, 
                    string textBoxRating, 
                    string textBoxLanguage, 
                    string textBoxRates, 
                    string textBoxAuthor, 
                    string textBoxPrice, 
                    string textBoxCharacters, 
                    string textBoxGenres, 
                    string textBoxSetting, 
                    string textBoxDescription, 
                    string textBoxTitle, 
                    string textBoxSeries, 
                    string textBoxPages, 
                    string textBoxFormat, 
                    string textBoxPublisher, 
                    string textBoxLink);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServiceBookManagementChannel : LibraryApp.ServiceBookManagement.IServiceBookManagement, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServiceBookManagementClient : System.ServiceModel.ClientBase<LibraryApp.ServiceBookManagement.IServiceBookManagement>, LibraryApp.ServiceBookManagement.IServiceBookManagement {
        
        public ServiceBookManagementClient() {
        }
        
        public ServiceBookManagementClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServiceBookManagementClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceBookManagementClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceBookManagementClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public bool IsBookDeleted(int bookId) {
            return base.Channel.IsBookDeleted(bookId);
        }
        
        public System.Threading.Tasks.Task<bool> IsBookDeletedAsync(int bookId) {
            return base.Channel.IsBookDeletedAsync(bookId);
        }
        
        public bool DeleteBook(int bookId) {
            return base.Channel.DeleteBook(bookId);
        }
        
        public System.Threading.Tasks.Task<bool> DeleteBookAsync(int bookId) {
            return base.Channel.DeleteBookAsync(bookId);
        }
        
        public bool RestoreBook(int bookId) {
            return base.Channel.RestoreBook(bookId);
        }
        
        public System.Threading.Tasks.Task<bool> RestoreBookAsync(int bookId) {
            return base.Channel.RestoreBookAsync(bookId);
        }
        
        public void AddNewBook(string textBoxRating, string textBoxLanguage, string textBoxRates, string textBoxAuthor, string textBoxPrice, string textBoxCharacters, string textBoxGenres, string textBoxSetting, string textBoxDescription, string textBoxTitle, string textBoxSeries, string textBoxPages, string textBoxFormat, string textBoxPublisher, string textBoxLink) {
            base.Channel.AddNewBook(textBoxRating, textBoxLanguage, textBoxRates, textBoxAuthor, textBoxPrice, textBoxCharacters, textBoxGenres, textBoxSetting, textBoxDescription, textBoxTitle, textBoxSeries, textBoxPages, textBoxFormat, textBoxPublisher, textBoxLink);
        }
        
        public System.Threading.Tasks.Task AddNewBookAsync(string textBoxRating, string textBoxLanguage, string textBoxRates, string textBoxAuthor, string textBoxPrice, string textBoxCharacters, string textBoxGenres, string textBoxSetting, string textBoxDescription, string textBoxTitle, string textBoxSeries, string textBoxPages, string textBoxFormat, string textBoxPublisher, string textBoxLink) {
            return base.Channel.AddNewBookAsync(textBoxRating, textBoxLanguage, textBoxRates, textBoxAuthor, textBoxPrice, textBoxCharacters, textBoxGenres, textBoxSetting, textBoxDescription, textBoxTitle, textBoxSeries, textBoxPages, textBoxFormat, textBoxPublisher, textBoxLink);
        }
        
        public void EditBook(
                    int bookId, 
                    string textBoxRating, 
                    string textBoxLanguage, 
                    string textBoxRates, 
                    string textBoxAuthor, 
                    string textBoxPrice, 
                    string textBoxCharacters, 
                    string textBoxGenres, 
                    string textBoxSetting, 
                    string textBoxDescription, 
                    string textBoxTitle, 
                    string textBoxSeries, 
                    string textBoxPages, 
                    string textBoxFormat, 
                    string textBoxPublisher, 
                    string textBoxLink) {
            base.Channel.EditBook(bookId, textBoxRating, textBoxLanguage, textBoxRates, textBoxAuthor, textBoxPrice, textBoxCharacters, textBoxGenres, textBoxSetting, textBoxDescription, textBoxTitle, textBoxSeries, textBoxPages, textBoxFormat, textBoxPublisher, textBoxLink);
        }
        
        public System.Threading.Tasks.Task EditBookAsync(
                    int bookId, 
                    string textBoxRating, 
                    string textBoxLanguage, 
                    string textBoxRates, 
                    string textBoxAuthor, 
                    string textBoxPrice, 
                    string textBoxCharacters, 
                    string textBoxGenres, 
                    string textBoxSetting, 
                    string textBoxDescription, 
                    string textBoxTitle, 
                    string textBoxSeries, 
                    string textBoxPages, 
                    string textBoxFormat, 
                    string textBoxPublisher, 
                    string textBoxLink) {
            return base.Channel.EditBookAsync(bookId, textBoxRating, textBoxLanguage, textBoxRates, textBoxAuthor, textBoxPrice, textBoxCharacters, textBoxGenres, textBoxSetting, textBoxDescription, textBoxTitle, textBoxSeries, textBoxPages, textBoxFormat, textBoxPublisher, textBoxLink);
        }
    }
}
